title: Personal presentation
author: Ovidio Duarte
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This GitHub page was made with the intention of present my personal portfolio, my interests and also my skills.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
